#!/bin/bash

######################################################## 
# 2022/09/17
# ok.xmonad@gmail.com
#
# atcoder cliのラッパー
########################################################

traning="/home/neko/WorkSpace/atcoder/"

cd $traning
acc new $1

ranger ${traning}$1

