#!/bin/bash

######################################################## 
# 2022/09/17
# ok.xmonad@gmail.com
#
# atcoder cliのラッパー
########################################################

traning="/home/neko/WorkSpace/competition/problems/"

cd $traning
acc new $1

cd ${traning}$1
ranger

