#!/bin/bash

######################################################## 
# 2024/04/09
# ok.xmonad@gmail.com
#
# atcoder cliのラッパー
########################################################

traning="/home/neko/WorkSpace/competition/novisteps/"

cd $traning
acc new $1

cd ${traning}$1
ranger

