#!/bin/sh

######################################################## 
# 2022/01/17
# ok.xmonad@gmail.com
#
# すくりーんしょっと
########################################################

output_filename=screenshot_$(date +%Y%m%d%H%M%S).png

maim -st 9999999 | convert - \( +clone -background black -shadow 80x3+5+5 \) +swap -background none -layers merge +repage ${output_filename}
